import random
import hashlib
from datetime import date

WORD_LIST = [
    "abandon", "ability", "absence", "absorb", "abstract", "abuse", "academy",
    "accept", "access", "accident", "account", "achieve", "acid", "acquire",
    "action", "active", "actor", "actual", "adapt", "addition", "address",
    "adjust", "admire", "admit", "adopt", "adult", "advance", "adventure",
    "advice", "afford", "afraid", "agency", "agent", "agree", "ahead",
    "aircraft", "alarm", "album", "alcohol", "alert", "alien", "align",
    "alive", "allow", "almost", "alone", "alpha", "alter", "amazing",
    "ambition", "amount", "ancient", "anger", "angle", "animal", "announce",
    "annual", "answer", "anxiety", "apart", "appeal", "appear", "apple",
    "apply", "approve", "arch", "arena", "argue", "arise", "armor",
    "army", "arrange", "arrest", "arrive", "arrow", "article", "artist",
    "aspect", "assault", "assert", "assess", "asset", "assign", "assist",
    "assume", "athlete", "atom", "attach", "attack", "attempt", "attend",
    "attract", "auction", "author", "autumn", "average", "avoid", "awake",
    "award", "aware", "awful", "axis", "baby", "balance", "ball",
    "banana", "band", "bank", "banner", "bar", "barrel", "barrier",
    "base", "basic", "basket", "bath", "battery", "battle", "beach",
    "beam", "bean", "bear", "beard", "beast", "beat", "beauty",
    "become", "bedroom", "begin", "behave", "belief", "belong", "bench",
    "benefit", "berry", "beyond", "bicycle", "bind", "biology", "bird",
    "birth", "bitter", "blade", "blame", "blanket", "blast", "bleed",
    "blend", "bless", "blind", "block", "blood", "blow", "board",
    "boat", "body", "bomb", "bond", "bone", "bonus", "border",
    "boring", "borrow", "boss", "bottle", "bottom", "bounce", "bowl",
    "brain", "branch", "brand", "brave", "bread", "break", "breath",
    "breed", "brick", "bridge", "bright", "bring", "broad", "broken",
    "brother", "brush", "bubble", "bucket", "budget", "build", "bullet",
    "burden", "burn", "burst", "butter", "button", "cabin", "cable",
    "cage", "cake", "calm", "camera", "camp", "campus", "cancel",
    "candle", "canvas", "capable", "capital", "capture", "carbon", "career",
    "careful", "cargo", "carpet", "carry", "castle", "casual", "catalog",
    "catch", "cattle", "cause", "ceiling", "cell", "center", "central",
    "century", "certain", "chain", "chair", "chalk", "chamber", "champion",
    "change", "channel", "chapter", "charge", "charity", "charm", "chart",
    "chase", "cheap", "check", "cheese", "chef", "cherry", "chest",
    "chicken", "chief", "child", "chip", "choice", "choose", "church",
    "circle", "citizen", "civil", "claim", "class", "classic", "clean",
    "clear", "clever", "cliff", "climate", "climb", "clinic", "clock",
    "close", "cloth", "cloud", "cluster", "coach", "coal", "coast",
    "code", "coffee", "coin", "cold", "collect", "college", "colony",
    "color", "column", "combine", "comfort", "command", "comment", "commit",
    "common", "company", "compare", "compete", "complex", "compose", "concept",
    "concern", "conduct", "confirm", "conflict", "connect", "consent", "consider",
    "consist", "console", "constant", "contact", "contain", "content", "contest",
    "context", "control", "convert", "convince", "cook", "cool", "copper",
    "copy", "core", "corner", "correct", "cosmic", "cotton", "council",
    "count", "country", "couple", "courage", "course", "cousin", "cover",
    "craft", "crash", "crazy", "cream", "create", "credit", "crew",
    "crime", "crisis", "critic", "crop", "cross", "crowd", "crown",
    "crucial", "cruel", "crush", "crystal", "culture", "cup", "cure",
    "curious", "current", "curtain", "curve", "custom", "cycle", "damage",
    "dance", "danger", "dare", "dark", "data", "dawn", "deal",
    "debate", "decade", "decent", "decide", "decline", "decorate", "deep",
    "default", "defeat", "defend", "define", "degree", "delay", "deliver",
    "demand", "demon", "denial", "dense", "deny", "depart", "depend",
    "deposit", "depth", "deputy", "derive", "desert", "design", "desire",
    "desk", "despair", "destroy", "detail", "detect", "develop", "device",
    "devote", "diamond", "diet", "differ", "digital", "dignity", "dinner",
    "direct", "dirty", "disable", "discuss", "disease", "dish", "dismiss",
    "display", "dispute", "distant", "divide", "doctor", "document", "dollar",
    "domain", "domestic", "done", "door", "double", "doubt", "draft",
    "dragon", "drama", "draw", "dream", "dress", "drift", "drink",
    "drive", "drop", "drum", "drunk", "dust", "duty", "dynamic",
    "eager", "earn", "earth", "ease", "east", "economy", "edge",
    "editor", "educate", "effect", "effort", "either", "elbow", "elderly",
    "elect", "elegant", "element", "embrace", "emerge", "emotion", "emperor",
    "empire", "employ", "empty", "enable", "encounter", "encourage", "endless",
    "enemy", "energy", "enforce", "engage", "engine", "enhance", "enjoy",
    "enormous", "enough", "ensure", "enter", "entire", "entry", "envelope",
    "episode", "equal", "equip", "era", "error", "escape", "essay",
    "essence", "estate", "eternal", "evening", "event", "evident", "evil",
    "evolve", "exact", "examine", "example", "exceed", "exchange", "excite",
    "exclude", "excuse", "execute", "exercise", "exhibit", "exist", "expand",
    "expect", "expense", "expert", "explain", "explode", "explore", "export",
    "expose", "extend", "extent", "extra", "extreme", "fabric", "face",
    "facility", "factor", "factory", "failure", "faith", "fall", "false",
    "fame", "family", "famous", "fancy", "fantasy", "farm", "fashion",
    "fast", "fate", "father", "fault", "favor", "fear", "feast",
    "feature", "federal", "feed", "feeling", "fellow", "female", "fence",
    "fever", "fiction", "field", "fierce", "fight", "figure", "fill",
    "film", "filter", "final", "finance", "finger", "finish", "fire",
    "firm", "fish", "fit", "flag", "flame", "flash", "flat",
    "flavor", "flee", "flesh", "flight", "float", "flood", "floor",
    "flower", "fluid", "flush", "focus", "fold", "follow", "food",
    "force", "foreign", "forest", "forever", "forget", "forgive", "formal",
    "formula", "fortune", "forward", "fossil", "foster", "found", "fox",
    "frame", "freedom", "freeze", "frequent", "fresh", "friend", "front",
    "frozen", "fruit", "fuel", "fulfill", "fun", "function", "fund",
    "funeral", "funny", "fur", "fury", "future", "gain", "galaxy",
    "gallery", "game", "gang", "gap", "garage", "garden", "garlic",
    "gate", "gather", "gear", "gender", "general", "generate", "genius",
    "gentle", "genuine", "gesture", "ghost", "giant", "gift", "girl",
    "glad", "glance", "glass", "global", "glory", "glove", "goal",
    "golden", "govern", "grace", "grade", "grain", "grand", "grant",
    "grass", "grave", "gravity", "great", "green", "grief", "grin",
    "grip", "grocery", "ground", "group", "grow", "growth", "guard",
    "guess", "guest", "guide", "guilt", "guitar", "gun", "habit",
    "hair", "half", "hall", "hammer", "hand", "handle", "hang",
    "happen", "happy", "harbor", "hard", "harvest", "hat", "hate",
    "haunt", "haven", "hazard", "head", "health", "heart", "heat",
    "heaven", "heavy", "height", "help", "herb", "hero", "hesitate",
    "hidden", "highway", "hill", "hint", "hire", "history", "hobby",
    "hold", "hole", "holiday", "hollow", "honest", "honor", "hook",
    "hope", "horizon", "horror", "horse", "host", "hotel", "hour",
    "house", "huge", "human", "humble", "humor", "hunger", "hunt",
    "hurry", "hurt", "husband", "ice", "idea", "identify", "ignore",
    "illegal", "image", "imagine", "immense", "immune", "impact", "imply",
    "import", "impose", "impress", "improve", "incident", "include", "income",
    "increase", "index", "indicate", "indoor", "industry", "infant", "inflict",
    "inform", "initial", "injury", "inner", "innocent", "input", "inquiry",
    "insect", "insert", "inside", "inspect", "inspire", "install", "instant",
    "instead", "intact", "intend", "interest", "internal", "internet", "interval",
    "invade", "invent", "invest", "invite", "involve", "iron", "island",
    "isolate", "issue", "item", "ivory", "jacket", "jail", "jaw",
    "jazz", "jewel", "joke", "journal", "journey", "joy", "judge",
    "juice", "jump", "jungle", "junior", "justice", "keen", "keep",
    "kernel", "key", "kick", "kind", "kingdom", "kiss", "kitchen",
    "knee", "knife", "knock", "know", "label", "labor", "ladder",
    "lake", "lamp", "land", "language", "laptop", "large", "laser",
    "last", "lateral", "laugh", "launch", "lava", "lawn", "lawyer",
    "layer", "layout", "lazy", "leader", "leaf", "league", "lean",
    "learn", "leather", "leave", "lecture", "legal", "legend", "leisure",
    "lemon", "length", "lens", "lesson", "letter", "level", "liberty",
    "library", "license", "life", "lift", "light", "limit", "line",
    "link", "lion", "lip", "liquid", "list", "listen", "little",
    "live", "load", "loan", "lobby", "local", "lock", "logic",
    "lonely", "long", "loop", "loss", "loud", "love", "loyal",
    "luck", "lumber", "lunch", "luxury", "machine", "mad", "magic",
    "magnet", "major", "mammal", "manage", "mandate", "manner", "manual",
    "maple", "marble", "march", "margin", "marine", "market", "marriage",
    "mask", "mass", "massive", "master", "match", "material", "matter",
    "maximum", "meadow", "mean", "measure", "meat", "media", "medicine",
    "medium", "melody", "member", "memory", "mention", "mentor", "mercy",
    "merge", "merit", "message", "metal", "method", "middle", "midnight",
    "might", "military", "million", "mind", "minimum", "minor", "minute",
    "miracle", "mirror", "misery", "miss", "mission", "mistake", "mix",
    "mobile", "model", "modern", "modify", "moment", "monitor", "monkey",
    "monster", "month", "mood", "moral", "morning", "mosquito", "mother",
    "motion", "motor", "mountain", "mouse", "mouth", "move", "movie",
    "much", "multiply", "muscle", "museum", "music", "must", "mutual",
    "mystery", "myth", "naive", "name", "napkin", "narrow", "nation",
    "nature", "near", "neat", "neck", "need", "negative", "neglect",
    "neither", "nephew", "nerve", "nest", "network", "neutral", "never",
    "noble", "noise", "nominee", "normal", "north", "notable", "note",
    "nothing", "notice", "novel", "nuclear", "number", "nurse", "object",
    "observe", "obtain", "obvious", "occur", "ocean", "odds", "offer",
    "office", "olive", "once", "onion", "open", "opera", "opinion",
    "oppose", "option", "orange", "orbit", "orchard", "order", "organ",
    "orient", "origin", "orphan", "ostrich", "other", "outdoor", "outer",
    "output", "outside", "oven", "over", "owner", "oxygen", "pace",
    "package", "paddle", "page", "pair", "palace", "palm", "panda",
    "panel", "panic", "parade", "parent", "park", "parrot", "part",
    "party", "pass", "patch", "path", "patient", "patrol", "pattern",
    "pause", "pave", "peace", "peanut", "pear", "peasant", "pelican",
    "penalty", "pencil", "people", "pepper", "perfect", "permit", "person",
    "pet", "phone", "photo", "phrase", "physical", "piano", "picnic",
    "picture", "piece", "pilot", "pine", "pioneer", "pipe", "pistol",
    "pitch", "pizza", "place", "planet", "plastic", "plate", "play",
    "please", "pledge", "pluck", "plug", "plunge", "poem", "poet",
    "point", "polar", "pole", "police", "pond", "pool", "popular",
    "portion", "position", "possible", "post", "potato", "pottery", "poverty",
    "powder", "power", "practice", "praise", "predict", "prefer", "prepare",
    "present", "press", "pretend", "pretty", "prevent", "price", "pride",
    "primary", "prince", "print", "prison", "private", "prize", "problem",
    "process", "produce", "profit", "program", "project", "promote", "proof",
    "property", "prosper", "protect", "proud", "provide", "public", "pull",
    "pulse", "pumpkin", "punch", "pupil", "puppy", "purchase", "pure",
    "purpose", "pursue", "push", "puzzle", "pyramid", "quality", "quarter",
    "queen", "question", "quick", "quiet", "quit", "quote", "rabbit",
    "race", "rack", "radar", "radio", "rail", "rain", "raise",
    "rally", "ramp", "ranch", "random", "range", "rapid", "rare",
    "rather", "raven", "raw", "razor", "reach", "react", "ready",
    "real", "reason", "rebel", "rebuild", "recall", "receive", "recipe",
    "record", "recycle", "reduce", "reflect", "reform", "refuse", "region",
    "regret", "regular", "reject", "relate", "release", "relief", "rely",
    "remain", "remember", "remind", "remove", "renew", "rent", "repair",
    "repeat", "replace", "report", "require", "rescue", "resemble", "resist",
    "resolve", "resource", "respond", "restore", "result", "retire", "retreat",
    "return", "reveal", "revenge", "review", "revolt", "reward", "rhythm",
    "rich", "ride", "rifle", "right", "rigid", "ring", "riot",
    "ripple", "risk", "ritual", "rival", "river", "road", "robot",
    "robust", "rocket", "romance", "roof", "rookie", "room", "rose",
    "rotate", "rough", "round", "route", "royal", "rubber", "rude",
    "rug", "rule", "rural", "rush", "saddle", "sadness", "safe",
    "salad", "salmon", "salon", "salt", "salute", "sample", "sand",
    "satisfy", "sauce", "save", "scale", "scatter", "scene", "scheme",
    "school", "science", "scissors", "score", "scout", "screen", "script",
    "sea", "search", "season", "seat", "secret", "section", "security",
    "seed", "select", "sell", "senior", "sense", "sentence", "series",
    "service", "session", "settle", "setup", "seven", "shadow", "shaft",
    "shallow", "shame", "shape", "share", "sharp", "shed", "shell",
    "shelter", "shift", "shine", "ship", "shock", "shoe", "shoot",
    "shop", "shoulder", "shove", "shrimp", "shuffle", "shy", "sibling",
    "sick", "side", "sight", "sign", "silent", "silk", "silly",
    "silver", "similar", "simple", "sing", "sister", "situate", "six",
    "size", "skill", "skin", "skirt", "skull", "slender", "slice",
    "slide", "slight", "slim", "slogan", "slow", "small", "smart",
    "smile", "smoke", "smooth", "snack", "snake", "snap", "snow",
    "soap", "soccer", "social", "sock", "soft", "solar", "soldier",
    "solid", "solution", "solve", "someone", "song", "sort", "soul",
    "sound", "source", "south", "space", "spare", "spatial", "spawn",
    "speak", "special", "speed", "spell", "spend", "sphere", "spider",
    "spike", "spirit", "split", "sponsor", "spoon", "sport", "spray",
    "spread", "spring", "square", "squeeze", "stable", "stadium", "staff",
    "stage", "stairs", "stamp", "stand", "start", "state", "station",
    "status", "stay", "steady", "steak", "steel", "stem", "step",
    "stick", "still", "stock", "stomach", "stone", "stool", "story",
    "stove", "strategy", "street", "strike", "strong", "struggle", "student",
    "stuff", "stumble", "style", "subject", "submit", "subtle", "success",
    "such", "sudden", "suffer", "sugar", "suggest", "suit", "summer",
    "sun", "sunset", "super", "supply", "supreme", "surface", "surge",
    "surprise", "surround", "survey", "suspect", "sustain", "swallow", "swamp",
    "swap", "swarm", "swear", "sweet", "swim", "swing", "switch",
    "sword", "symbol", "symptom", "system", "table", "tackle", "tail",
    "talent", "talk", "tank", "tape", "target", "task", "tattoo",
    "taxi", "teach", "team", "tell", "temple", "tenant", "tend",
    "tension", "term", "test", "text", "thank", "theme", "theory",
    "therapy", "thing", "thought", "three", "thrive", "throw", "thumb",
    "thunder", "ticket", "tide", "tiger", "tilt", "timber", "time",
    "tiny", "tip", "tired", "tissue", "title", "toast", "tobacco",
    "today", "toddler", "together", "token", "tomato", "tomorrow", "tone",
    "tongue", "tonight", "tool", "tooth", "top", "topic", "torch",
    "tornado", "tortoise", "total", "tourist", "toward", "tower", "town",
    "toy", "track", "trade", "traffic", "tragic", "train", "transfer",
    "trap", "trash", "travel", "tray", "treat", "tree", "trend",
    "trial", "tribe", "trick", "trigger", "trim", "triple", "trophy",
    "trouble", "truck", "truly", "trumpet", "trust", "truth", "try",
    "tube", "tumble", "tunnel", "turkey", "turn", "turtle", "twelve",
    "twin", "twist", "type", "typical", "ugly", "umbrella", "unable",
    "unaware", "uncle", "uncover", "under", "unfair", "unfold", "unhappy",
    "uniform", "unique", "unit", "universe", "unknown", "unlock", "until",
    "unusual", "unveil", "update", "upgrade", "upper", "upset", "urban",
    "usage", "useful", "usual", "utility", "vacant", "vacuum", "valid",
    "valley", "valve", "vanish", "vapor", "various", "vast", "vault",
    "vehicle", "vendor", "venture", "verb", "verify", "version", "vessel",
    "veteran", "viable", "victory", "video", "view", "village", "vintage",
    "violin", "virtual", "virus", "visa", "visit", "visual", "vital",
    "vivid", "vocal", "voice", "volcano", "volume", "vote", "voyage",
    "wage", "wagon", "wait", "walk", "wall", "walnut", "wander",
    "warfare", "warm", "warrior", "wash", "waste", "water", "wave",
    "wealth", "weapon", "wear", "weather", "wedding", "weekend", "welcome",
    "west", "wheat", "wheel", "whisper", "wide", "width", "wife",
    "wild", "will", "win", "window", "wine", "wing", "winner",
    "winter", "wire", "wisdom", "wise", "wish", "witness", "wolf",
    "woman", "wonder", "wood", "wool", "word", "work", "world",
    "worry", "worth", "wrap", "wreck", "wrestle", "wrist", "write",
    "wrong", "yard", "year", "yellow", "young", "youth", "zebra",
    "zero", "zone", "possess", "own", "belong", "property", "spot",
]

# Deduplicate
WORD_LIST = sorted(set(WORD_LIST))


def _date_seed(d: date) -> int:
    h = hashlib.sha256(d.isoformat().encode()).hexdigest()
    return int(h[:8], 16)


def get_daily_pair(d: date | None = None) -> tuple[str, str]:
    if d is None:
        d = date.today()
    rng = random.Random(_date_seed(d))
    a, b = rng.sample(WORD_LIST, 2)
    return a, b


def get_random_pair() -> tuple[str, str]:
    a, b = random.sample(WORD_LIST, 2)
    return a, b
